# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Where the Redfern Codes
email: trevorredfern@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Coding, Learning, and Organizational Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wheretheredfern.codes" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: CodesWhere
twitch_username: wheretheredferncodes
github_username:  tredfern
author: 
  name: Trevor Redfern
  email: trevorredfern@gmail.com
  picture: /assets/images/profile.jpg
# Build settings
markdown: kramdown
remote_theme:  "mmistakes/so-simple-theme@3.2.0"
google_analytics: G-NQ3FM6486G
# remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
read_time: true

footer_links:
  - title: twitch
    url: https://twitch.tv/wheretheredferncodes
    icon: fab fa-twitch
  - title: twitter
    url: https://twitter.com/CodesWhere
    icon: fab fa-twitter-square
  - title: github
    url: https://github.com/tredfern
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
